// Tasks Actions
export const GET_ALL_TASKS_REQUEST = 'GET_ALL_TASKS_REQUEST';
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS';
export const GET_ALL_TASKS_FAILURE = 'GET_ALL_TASKS_FAILURE';
export const GET_ALL_TASKS_CLEAR_STATE = 'GET_ALL_TASKS_CLEAR_STATE';

export const NEW_TASK_REQUEST = 'NEW_TASK_REQUEST';
export const NEW_TASK_SUCCESS = 'NEW_TASK_SUCCESS';
export const NEW_TASK_FAILURE = 'NEW_TASK_FAILURE';
export const NEW_TASK_CLEAR_STATE = 'NEW_TASK_CLEAR_STATE';

// Todo Actions
export const GET_ALL_TODO_REQUEST = 'GET_ALL_TODO_REQUEST';
export const GET_ALL_TODO_SUCCESS = 'GET_ALL_TODO_SUCCESS';
export const GET_ALL_TODO_FAILURE = 'GET_ALL_TODO_FAILURE';
export const GET_ALL_TODO_CLEAR_STATE = 'GET_ALL_TODO_CLEAR_STATE';

export const NEW_TODO_REQUEST = 'NEW_TODO_REQUEST';
export const NEW_TODO_SUCCESS = 'NEW_TODO_SUCCESS';
export const NEW_TODO_FAILURE = 'NEW_TODO_FAILURE';
export const NEW_TODO_CLEAR_STATE = 'NEW_TODO_CLEAR_STATE';

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE';
export const UPDATE_TODO_CLEAR_STATE = 'UPDATE_TODO_CLEAR_STATE';

// Theme Actions
export const UPDATE_APP_THEME = 'UPDATE_APP_THEME';
