version: '3'

services:
  mongodb:
    image: mongo:latest
    command: --serviceExecutor adaptive
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

  api:
    container_name: todo-api
    restart: on-failure
    build: .
    command: bash -c "rm -rf ./gin-bin && gin -a 8080 --all -i -x uploads run main.go"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - mongodb

volumes:
  mongodb:
